// Hand-authored to match the Supabase schema. Once a local DB is running, this
// file is regenerated by `pnpm db:types` (supabase gen types typescript --local).
// Covers the tables/views/functions the client currently uses.

import type {
  UserRole,
  VerificationStatus,
  ListingStatus,
  FuelType,
  TransmissionType,
  BodyType,
  EnquiryStatus,
  NotificationType,
} from './enums.js';

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Timestamps = { created_at: string };

export interface Database {
  public: {
    Tables: {
      cities: {
        Row: { id: string; name: string; state: string; slug: string } & Timestamps;
        Insert: { id?: string; name: string; state: string; slug: string; created_at?: string };
        Update: Partial<Database['public']['Tables']['cities']['Insert']>;
        Relationships: [];
      };
      car_makes: {
        Row: { id: string; name: string; slug: string; logo_url: string | null } & Timestamps;
        Insert: { id?: string; name: string; slug: string; logo_url?: string | null; created_at?: string };
        Update: Partial<Database['public']['Tables']['car_makes']['Insert']>;
        Relationships: [];
      };
      car_models: {
        Row: { id: string; make_id: string; name: string; slug: string; body_type: BodyType | null } & Timestamps;
        Insert: { id?: string; make_id: string; name: string; slug: string; body_type?: BodyType | null; created_at?: string };
        Update: Partial<Database['public']['Tables']['car_models']['Insert']>;
        Relationships: [];
      };
      car_variants: {
        Row: { id: string; model_id: string; name: string; fuel: FuelType | null; transmission: TransmissionType | null } & Timestamps;
        Insert: { id?: string; model_id: string; name: string; fuel?: FuelType | null; transmission?: TransmissionType | null; created_at?: string };
        Update: Partial<Database['public']['Tables']['car_variants']['Insert']>;
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string; full_name: string | null; phone: string | null; email: string | null;
          city_id: string | null; avatar_url: string | null; role: UserRole;
          created_at: string; updated_at: string;
        };
        Insert: { id: string; full_name?: string | null; phone?: string | null; email?: string | null; city_id?: string | null; avatar_url?: string | null; role?: UserRole };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
        Relationships: [];
      };
      dealers: {
        Row: {
          id: string; profile_id: string; business_name: string; gst_number: string | null;
          address: string | null; city_id: string | null; verification_status: VerificationStatus;
          verified_at: string | null; created_at: string; updated_at: string;
        };
        Insert: { id?: string; profile_id: string; business_name: string; gst_number?: string | null; address?: string | null; city_id?: string | null };
        Update: Partial<Database['public']['Tables']['dealers']['Insert']> & { verification_status?: VerificationStatus; verified_at?: string | null };
        Relationships: [];
      };
      listings: {
        Row: {
          id: string; seller_id: string; make_id: string; model_id: string; variant_id: string | null;
          title: string; year: number; price: number; km_driven: number; owners: number;
          fuel: FuelType; transmission: TransmissionType; body_type: BodyType | null; color: string | null;
          registration_city_id: string | null; registration_number: string | null; description: string | null;
          status: ListingStatus; is_dealer_listing: boolean; view_count: number; search_vector: string | null;
          created_at: string; updated_at: string; published_at: string | null; sold_at: string | null; expires_at: string | null;
        };
        Insert: {
          id?: string; seller_id: string; make_id: string; model_id: string; variant_id?: string | null;
          title: string; year: number; price: number; km_driven: number; owners?: number;
          fuel: FuelType; transmission: TransmissionType; body_type?: BodyType | null; color?: string | null;
          registration_city_id?: string | null; registration_number?: string | null; description?: string | null;
          status?: ListingStatus; is_dealer_listing?: boolean;
        };
        Update: Partial<Database['public']['Tables']['listings']['Insert']>;
        Relationships: [];
      };
      listing_photos: {
        Row: { id: string; listing_id: string; storage_path: string; position: number; is_cover: boolean } & Timestamps;
        Insert: { id?: string; listing_id: string; storage_path: string; position?: number; is_cover?: boolean };
        Update: Partial<Database['public']['Tables']['listing_photos']['Insert']>;
        Relationships: [];
      };
      favorites: {
        Row: { user_id: string; listing_id: string } & Timestamps;
        Insert: { user_id: string; listing_id: string; created_at?: string };
        Update: Partial<Database['public']['Tables']['favorites']['Insert']>;
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string; listing_id: string; buyer_id: string; seller_id: string; message: string | null;
          phone_revealed: boolean; status: EnquiryStatus; created_at: string;
        };
        Insert: { id?: string; listing_id: string; buyer_id: string; seller_id: string; message?: string | null };
        Update: { status?: EnquiryStatus };
        Relationships: [];
      };
      chat_threads: {
        Row: { id: string; listing_id: string; buyer_id: string; seller_id: string; created_at: string; last_message_at: string };
        Insert: { id?: string; listing_id: string; buyer_id: string; seller_id: string };
        Update: { last_message_at?: string };
        Relationships: [];
      };
      chat_messages: {
        Row: { id: string; thread_id: string; sender_id: string; body: string; read_at: string | null; created_at: string };
        Insert: { id?: string; thread_id: string; sender_id: string; body: string };
        Update: { read_at?: string | null };
        Relationships: [];
      };
      notifications: {
        Row: { id: string; user_id: string; type: NotificationType; title: string; body: string | null; data: Json | null; read_at: string | null; created_at: string };
        Insert: { id?: string; user_id: string; type: NotificationType; title: string; body?: string | null; data?: Json | null };
        Update: { read_at?: string | null };
        Relationships: [];
      };
    };
    Views: {
      seller_public_profiles: {
        Row: {
          id: string | null; full_name: string | null; avatar_url: string | null; role: UserRole | null;
          city_id: string | null; city_name: string | null; is_verified_dealer: boolean | null; business_name: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      create_enquiry: {
        Args: { p_listing_id: string; p_message?: string | null };
        Returns: { enquiry_id: string; seller_name: string | null; seller_phone: string | null }[];
      };
      log_listing_view: {
        Args: { p_listing_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      user_role: UserRole;
      verification_status: VerificationStatus;
      listing_status: ListingStatus;
      fuel_type: FuelType;
      transmission_type: TransmissionType;
      body_type: BodyType;
      enquiry_status: EnquiryStatus;
      notification_type: NotificationType;
    };
    CompositeTypes: Record<string, never>;
  };
}
